version: "3.9"
services:
  judo_techniques_bot:
    container_name: judo_techniques_bot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/
      # - ./logs:/app/logs
    stdin_open: true
    tty: true
