# DEPRECATED: This is no longer used
version: "3.9"
services:
  judo_techniques_bot:
    container_name: judo_techniques_bot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URI: postgresql+psycopg2://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      USER_AGENT: ${USER_AGENT}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      REDDIT_USERNAME: ${REDDIT_USERNAME}
      REDDIT_PASSWORD: ${REDDIT_PASSWORD}
      SUBREDDITS: ${SUBREDDITS}
      SENTRY_DSN: ${SENTRY_DSN}
    volumes:
      - .:/app/
    stdin_open: true
    restart: always
    tty: true
