"""empty message

Revision ID: 1dcd8a18bfd5
Revises: 2eecb7a44adb
Create Date: 2021-07-31 23:00:02.547086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dcd8a18bfd5'
down_revision = '2eecb7a44adb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('techniques',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('japanese_display_name', sa.String(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('created_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('techniques')
    # ### end Alembic commands ###
