"""empty message

Revision ID: eed8d5f47027
Revises: 1dcd8a18bfd5
Create Date: 2021-07-31 23:05:11.343912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eed8d5f47027'
down_revision = '1dcd8a18bfd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mention_events',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('technique_id', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(length=20), nullable=True),
    sa.Column('translated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['technique_id'], ['techniques.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mention_events')
    # ### end Alembic commands ###
