"""empty message

Revision ID: bdcfc99aeebf
Revises: eed8d5f47027
Create Date: 2021-07-31 23:10:55.661530

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bdcfc99aeebf'
down_revision = 'eed8d5f47027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mention_events', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('mention_events', 'datetime')
    op.add_column('techniques', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('techniques', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('techniques', 'updated_datetime')
    op.drop_column('techniques', 'created_datetime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('techniques', sa.Column('created_datetime', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('techniques', sa.Column('updated_datetime', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('techniques', 'updated_at')
    op.drop_column('techniques', 'created_at')
    op.add_column('mention_events', sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('mention_events', 'created_at')
    # ### end Alembic commands ###
