"""empty message

Revision ID: 031968931281
Revises: 762e4a7e7803
Create Date: 2021-08-19 23:23:17.141171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031968931281'
down_revision = '762e4a7e7803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mention_events', sa.Column('name_variant', sa.String(), nullable=True))
    op.add_column('mention_events', sa.Column('comment_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mention_events', 'comment_url')
    op.drop_column('mention_events', 'name_variant')
    # ### end Alembic commands ###
