"""empty message

Revision ID: 762e4a7e7803
Revises: ecdfd2527ba7
Create Date: 2021-08-01 01:47:15.134325

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "762e4a7e7803"
down_revision = "ecdfd2527ba7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "techniques", "video_url", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "techniques", "video_url", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###
