"""empty message

Revision ID: 60f987eb8df0
Revises: 031968931281
Create Date: 2021-09-22 00:30:31.857095

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "60f987eb8df0"
down_revision = "031968931281"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "techniques", "video_url", existing_type=sa.VARCHAR(), nullable=True
    )
    table_name = sa.sql.table("techniques", sa.Column("video_url", sa.VARCHAR()))
    op.execute(
        table_name.update().where(table_name.c.video_url == "").values(video_url=None)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    table_name = sa.sql.table("techniques", sa.Column("video_url", sa.VARCHAR()))
    op.execute(
        table_name.update()
        .where(lambda: table_name.c.video_url is None)
        .values(video_url="")
    )
    op.alter_column(
        "techniques", "video_url", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
