"""empty message

Revision ID: ecdfd2527ba7
Revises: 4fa0d71e3598
Create Date: 2021-08-01 00:43:24.522317

"""

from alembic import op
import sqlalchemy as sa  # noqa: F401


# revision identifiers, used by Alembic.
revision = "ecdfd2527ba7"
down_revision = "4fa0d71e3598"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "techniques", ["japanese_display_name"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "techniques", type_="unique")  # ty:ignore[invalid-argument-type]
    # ### end Alembic commands ###
