name: "Terraform Apply"

on:
  workflow_call:
  workflow_dispatch:

env:
  TERRAFORM_CLOUD_TOKENS: app.terraform.io=${{ secrets.TF_API_TOKEN }}

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: ./terraform
          workspace: "judo-techniques-bot"
          auto_approve: true
          replace: |
            aws_launch_template.launch_template
            aws_ecs_task_definition.jtb_task_definition
